service: csv-image-processing-app
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 512
  timeout: 15
  tracing:
    lambda: true
  logRetentionInDays: 14
  httpApi:
    cors: true
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    UPSTASH_REDIS_URL: ${env:UPSTASH_REDIS_URL}
    UPSTASH_REDIS_TOKEN: ${env:UPSTASH_REDIS_TOKEN}
    WEBHOOK_URL: ${env:WEBHOOK_URL}
    S3_BUCKET: ${env:S3_BUCKET}
    NODE_ENV: production

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource:
            - arn:aws:s3:::${env:S3_BUCKET}/*
        - Effect: Allow
          Action:
            - logs:*
          Resource: "*"

functions:
  app:
    handler: src/lambda.handler
    memorySize: 1024
    timeout: 30
    events:
      - httpApi:
          path: /{proxy+}
          method: "*"
          

package:
  individually: true
  patterns:
    - "src/**"
    - "package.json"
    - "package-lock.json"
    - "node_modules/**"
    - "!node_modules/sharp/build/Release/!(sharp-linux-x64.node)"
    - "!test/**"
    - "!.env"
    - "!README.md"
    - "!.gitignore"

plugins:
  - serverless-offline
